bin:
  asm: cc
  cc: gcc-4.8
  ccache: ccache
  cxx: g++-4.8
  make: make
  pump: distcc-pump
env:
  ccache:
    enabled: false
  cotire:
    enabled: false
  distcc:
    # For local network builds. - N3X
    enabled: false
    hosts:
      192.168.9.139:
        max-jobs: 1
        opts:
        - lzo
        - cpp
      localhost:
        max-jobs: 5
        opts:
        - lzo
        - cpp
  cmake:
    flags:
      PCRE_SUPPORT_UTF: On
  make:
    flags: []
    jobs: 5
  packaging:
    enabled: true
    maintainer: Rob Nelson <nexisentertainment@gmail.com>
    packages:
      debian/jessie: true
      debian/wheezy: false
    # Requires ~/.gpass, with your passkey inside.
    repo-deploy: true
      
paths:
  install: /tmp/hhvm-install
  package: /tmp/hhvm-package
  source: ../hhvm
  exts:
    hhvm-pgsql: '../hhvm-pgsql'
